### ISSUE TITLE
where 'enum Viewers' to put in?

### ISSUE THREAD

**Issue by esafata** [dm1sh/react-eventful-calendar#1]
where 'enum Viewers' to put in?

**Comment by dm1sh** [comment]
You use it to set initialViewer property of Calendar component

**Comment by esafata** [comment]
initialViewer={Viewers.MonthViewer} 
or 
initialViewer={Viewers.DayViewer}

--------

enum Viewers {
  MonthViewer, // Month view
  DayViewer, // Single day view
}

that is just definition, so not for write to the code

**Comment by dm1sh** [comment]
Yes, it just shows all possible enum values
